### PR TITLE
Create remove-page-templates.php

### PR DESCRIPTION
**Pull request by IanDelMar**

### CODE REVIEW

**Comment by 0dp** [comment]
Is this PR addressing an issue?

**Comment by IanDelMar** [comment]
Nope! It's just part of a snippet collection for the child theme.

**Comment by 0dp** [comment]
Is there a snippet collection?

**Comment by IanDelMar** [comment]
Not yet. I thought it would be nice to provide the answers to raised questions about modifying the child theme as snippets. I filed the concerning PRs under a not yet existing directory called 'snippets'.

**Comment by 0dp** [comment]
@understrap/documentation-team please advice

**Comment by IanDelMar** [comment]
I created a branch containing all the files to make it more evident. I could close all the PRs and make on from that branch.

See https://github.com/IanDelMar/understrap-child/tree/snippet-collection

**Comment by Thomas-A-Reinert** [comment]
hi there. my 2 cent:

- _is this code actually being used anywhere in the existing templates?_ No, it´s not.
- _will anyone know what the new folder "snippets" is or even look into it_? Probably not.
- _does it improve the theme?_ Nope. See first two questions.

It would more likely better fit into documentation or anywhere else. But I would downvote it for inclusion in the basic theme/child theme.

**Comment by IanDelMar** [comment]
Though I disagree with the answers and the questions (what's the point of the snippets? of course they aren't used in the templates), I'm totally fine with not including them.

**Pull request closed without merging**
