### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by fschoenfeldt**
I updated all dependencies to their latest version, including bootstrap:

```
$ ncu -u
Upgrading /understrap-child/package.json
[====================] 27/27 100%

 bootstrap           ^4.3.1  →   ^4.4.1 
 browser-sync       ^2.26.3  →  ^2.26.7 
 del                 ^4.1.0  →   ^5.1.0 
 gulp                ^4.0.0  →   ^4.0.2 
 gulp-autoprefixer   ^6.0.0  →   ^7.0.1 
 gulp-clean-css      ^4.0.0  →   ^4.2.0 
 gulp-ignore         ^2.0.2  →   ^3.0.0 
 gulp-imagemin       ^5.0.3  →   ^7.1.0 
 gulp-rename         ^1.4.0  →   ^2.0.0 
 gulp-rimraf         ^0.2.2  →   ^1.0.0 
 merge2              ^1.2.3  →   ^1.3.0 
 popper.js          ^1.15.0  →  ^1.16.1 
 understrap          ^0.9.1  →   ^0.9.3 

Run npm install to install new versions.
```

I ran into an error though that's also with the upstream version:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.9.3 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the understrap@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I just ran `gulp copy-assets` manually.

### CODE REVIEW

**Comment by Thomas-A-Reinert** [comment]
Well, got to try that in a certain environment to make sure it works "out of the box" and with new/old parents as well. Can´t/won´t  promise anything though. We´re no longer maintaing this project.

**Comment by lbriet** [comment]
@Thomas-A-Reinert - just to check; you're no longer maintaining understap-child (but understrap is still safe? ;) )?

**Comment by 0dp** [comment]
@lbriet Thomas is not the maintainer of the projects @UnderstrapFramework is.
What he means is that the child theme have not gotten any love in a long time

**Comment by Thomas-A-Reinert** [comment]
To clarify: Project understrap got **bought** by "_understrapframework_". And he never ever contributed to the project, but tries to turn it into a "freemium software" as https://www.linkedin.com/in/alex-booth-474055b0 says.

That means that he also cut off ANY connections from the original understrap website to this repo and doesn´t seem to be able/willing to merge any user contributions at all too. At least he lacks any transparency upon his future plan, including a roadmap. And we really, really tried to get him aboard. I can also prove this if neccessary. 

Thats ALL things we tried to get to know from him since last september - without any effect at all.

And as @0dp already said: No i´m not and never was the maintainer of this project. Wish I was and things would´ve turned out differently.

So far, we all don´t know since we don´t get any honest feedback from the project maintainer who seems to turn that FOSS project into a milking cow. He just won´t answer according to our experience.

So far, UnderStrap is good to go. Maybe not up to the latest standard concerning WooCommerce, but search for it and you´ll find solutions here in the issue tracker.

Looking into my crystal ball I can tell you that we - the ORIGINAL contributors - won´t leave you alone. Not on this repo, not under the name of "understrap", but fully compatible. Because we´re totally fed up how things are being handled here.

**Comment by nvjacobo** [comment]
> To clarify: Project understrap got **bought** by "_understrapframework_". And he never ever contributed to the project, but tries to turn it into a "freemium software" as https://www.linkedin.com/in/alex-booth-474055b0 says.
> 
> That means that he also cut off ANY connections from the original understrap website to this repo and doesn´t seem to be able/willing to merge any user contributions at all too. At least he lacks any transparency upon his future plan, including a roadmap. And we really, really tried to get him aboard. I can also prove this if neccessary.
> 
> Thats ALL things we tried to get to know from him since last september - without any effect at all.
> 
> And as @0dp already said: No i´m not and never was the maintainer of this project. Wish I was and things would´ve turned out differently.
> 
> So far, we all don´t know since we don´t get any honest feedback from the project maintainer who seems to turn that FOSS project into a milking cow. He just won´t answer according to our experience.
> 
> So far, UnderStrap is good to go. Maybe not up to the latest standard concerning WooCommerce, but search for it and you´ll find solutions here in the issue tracker.
> 
> Looking into my crystal ball I can tell you that we - the ORIGINAL contributors - won´t leave you alone. Not on this repo, not under the name of "understrap", but fully compatible. Because we´re totally fed up how things are being handled here.

Thanks for this clarification @Thomas-A-Reinert. I am sad to hear that.  

What do you recommend for Understrap-child users?

**Comment by Thomas-A-Reinert** [comment]
Just saying: @0dp  is also one of the core contributors of the core/child theme. 
And we´re ALL kinda pissed off the development and issue-management of UnderStrap core and child. Really. And we´re also kinda sad about it. But we don´t know about any solution for it now.

That´s a pity and we (the core devs) really don´t want to see our project to die.
So that´s the reason why we´re trying to get a fork of the main repo to go ahead. And THEN a repo for the child theme. Both SHOULD be compatible with the main repo. We just gotta figure out a way on how to manage this and how to make users switch from one repo to another, whilst keeping everything up to date.

That´s our main concern right now. And to keep it compatible with the WORDPRESS-REPO. Right now, we don´t see any possibility to make that change.

We´re trying our best, but according to the situation ( corona and everything etc) we won´t promise anything

**Comment by bacoords** [comment]
Hi all, 

I'm closing this as we've updated all dependencies in line with Understrap 0.9.6 and cleaned up the issues surrounding the gulp copy-assets (based on the parent theme). 

Understrap child is now in active development and welcomes all contributors and any new PRs.

**Pull request closed without merging**
