### PR TITLE
Updates to entire build process and dependencies

### PR DESCRIPTION
**Pull request by bacoords**
Hi all, 

This is almost a full update of the dependencies and assets in understrap-child to bring it into line of the latest version of Understrap (0.9.6 at time of writing this). 

This includes:
- updating the npm dev depencies to match 0.9.6, so the latest BS4, Gulp, etc
- updating the npm install and gulp build processes so that they actually work
- compiling the newer assets
- various updates to the readme and package.json to reflect the correct information

### CODE REVIEW

**Comment by Thomas-A-Reinert** [comment]
This will need to be tested. EXTREMELY.

Brian Coords ***@***.***> schrieb am Do., 17. Juni 2021,
19:08:

**Comment by Thomas-A-Reinert** [comment]
Don't merge yet. Have it tested first-hand.

Brian Coords ***@***.***> schrieb am Do., 17. Juni 2021,
19:54:

**Comment by Thomas-A-Reinert** [comment]
I propose a test-branch or something.

Thomas A. Reinert ***@***.***> schrieb am Do., 17. Juni 2021,
19:57:

**Comment by 0dp** [comment]
I agree. Should probably have left it a day or two for review

**Comment by bacoords** [comment]
@Thomas-A-Reinert Sorry - just missed your comments- and you're probably right that there was no rush to merge. 

The last release was over two years ago and our experience has generally been that this starter child theme is nonfunctional- it requires a lot of work to even get it up and running for each build. The main updates here were just pulling all of the latest BS assets and updating Gulp to be more in line with the parent theme. Agree that we'll keep testing/reviewing, but just wanted to at least have something somewhat up-to-date and functional available when people click 'download' as this is really the only free child starter theme available.

**Comment by Thomas-A-Reinert** [comment]
@bacoords  - just don´t follow the way of the former dick. he would have merged ANYTHING because he could/would have never ever checked what the payload is unless he injected his own shit.

**Comment by Thomas-A-Reinert** [comment]
No need to hurry on some TWO YEARS STALE BRANCHES: 
Dudes, really. come up to par to the lastest release before you´re trying to judge things.

**Comment by howarddc** [comment]
Hey @Thomas-A-Reinert,

We totally hear you that there's plenty of bad blood with the previous managers, but I want to put that behind us, including not cursing about the previous owner on GitHub. Let's talk code but not make personal insults in the GitHub conversation from here on out. 

Brian, Dane and I will test this release thoroughly this week and will also look forward to any notes or bugs you find; so far it seems to be an improvement since our team had been basically unable to use the child theme previously due to errors and dependency issues that are now mostly resolved.

**Pull request merged**
