### PR TITLE
Dependencies update and migration to gulp 4

### PR DESCRIPTION
**Pull request by KenEucker**
I updated all of the node packages included in this project. I also updated the gulpfile to use gulp 4.

This PR also includes a compile task that I use for my own purposes.

Tests may follow.

### CODE REVIEW

**Comment by 0dp** [comment]
Hey Ken, great to see others keen on updating understrap to gulp4.

This PR is on the child theme only and I think it would be best if you also opened a PR on the main theme.

Great work!

**Comment by KenEucker** [comment]
@0dp 

Thanks for pointing that out! I've since forked and updated understrap on my account and have attempted to create a PR there, unfortunately github is having trouble posting my PR. I will try again later.

**Comment by 0dp** [comment]
Yeah, there have already been several attempts to introduce gulp4.

**Comment by KenEucker** [comment]
Thank you @holger1411 !

**Comment by KenEucker** [comment]
@holger1411 I just noticed that I'd left a console log in there where I shouldn't have:

https://github.com/understrap/understrap-child/blob/master/gulpfile.js#L221

I'd make a pull request but my fork has currently diverged to include browserify, so I cannot.

Cheers,

**Pull request merged**
